language: r

warnings_are_errors: true
r_check_args: --as-cran
sudo: required

r_binary_packages:
 - testthat
 - DBI
 - rentrez
 - RSQLite
 - RCurl
 - R.utils
 - crayon
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
on_failure: always
